grafana:
  enabled: true
  adminPassword: "admin123"
  service:
    type: NodePort
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100
      access: proxy
      isDefault: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
      - job_name: choco-api
        static_configs:
          - targets: ["api-service.choco.svc.cluster.local:5000"]
        metrics_path: /metrics