apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: choco-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thinhvpg2410/choco-k8s.git
    targetRevision: staging
    path: charts/choco
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: choco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true