apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: choco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: thinhvpg2410/choco-api:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: choco-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: choco-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: choco-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: choco
spec:
  selector:
    app: api
  ports:
    - port: 5000
      targetPort: 5000